--------------------------------------------------------
--  File creato - mercoledì-agosto-22-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CITTA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."CITTA" 
   (	"NOME_CITTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EVENTO" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"LUOGO" VARCHAR2(20 BYTE), 
	"DATA" DATE, 
	"PREZZO" FLOAT(126), 
	"DESCRIZIONE" VARCHAR2(280 BYTE), 
	"TIPOLOGIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTO_MUSICALE
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EVENTO_MUSICALE" 
   (	"ID" NUMBER, 
	"ARTISTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENTO_SPORTIVO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."EVENTO_SPORTIVO" 
   (	"ID" NUMBER, 
	"SPORT" VARCHAR2(20 BYTE), 
	"PARTECIPANTE1" VARCHAR2(20 BYTE), 
	"PARTECIPANTE2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table IMPIEGATO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."IMPIEGATO" 
   (	"ID" NUMBER, 
	"CODICE_FISCALE" VARCHAR2(16 BYTE), 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"DATA_ASSUNZIONE" DATE, 
	"STIPENDIO" FLOAT(126), 
	"EMAIL" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LUOGO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."LUOGO" 
   (	"NOME_LUOGO" VARCHAR2(20 BYTE), 
	"CITTA" VARCHAR2(20 BYTE), 
	"NUM_POSTI" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "ADMIN"."PERSONA" 
   (	"CODICE_FISCALE" VARCHAR2(16 BYTE), 
	"NOME" VARCHAR2(20 BYTE), 
	"COGNOME" VARCHAR2(20 BYTE), 
	"DATA_NASCITA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPORT
--------------------------------------------------------

  CREATE TABLE "ADMIN"."SPORT" 
   (	"NOME_SPORT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPOLOGIA_EVENTO
--------------------------------------------------------

  CREATE TABLE "ADMIN"."TIPOLOGIA_EVENTO" 
   (	"TIPOLOGIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for View VIEWIMPIEGATO
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "ADMIN"."VIEWIMPIEGATO" ("ID", "CODICE_FISCALE", "NOME", "COGNOME", "USERNAME", "PASSWORD", "DATA_ASSUNZIONE", "STIPENDIO", "EMAIL", "TELEFONO") AS 
  SELECT 
    IMPIEGATO.ID, PERSONA.CODICE_FISCALE, PERSONA.NOME, PERSONA.COGNOME, IMPIEGATO.USERNAME, IMPIEGATO.PASSWORD, IMPIEGATO.DATA_ASSUNZIONE, IMPIEGATO.STIPENDIO, IMPIEGATO.EMAIL, IMPIEGATO.TELEFONO
FROM 
    IMPIEGATO JOIN PERSONA ON IMPIEGATO.CODICE_FISCALE = PERSONA.CODICE_FISCALE
;
REM INSERTING into ADMIN.CITTA
SET DEFINE OFF;
Insert into ADMIN.CITTA (NOME_CITTA) values ('NAPOLI');
Insert into ADMIN.CITTA (NOME_CITTA) values ('ROMA');
Insert into ADMIN.CITTA (NOME_CITTA) values ('MILANO');
Insert into ADMIN.CITTA (NOME_CITTA) values ('BOLOGNA');
Insert into ADMIN.CITTA (NOME_CITTA) values ('TORINO');
Insert into ADMIN.CITTA (NOME_CITTA) values ('VENEZIA');
Insert into ADMIN.CITTA (NOME_CITTA) values ('VERONA');
Insert into ADMIN.CITTA (NOME_CITTA) values ('FIRENZE');
REM INSERTING into ADMIN.EVENTO
SET DEFINE OFF;
REM INSERTING into ADMIN.EVENTO_MUSICALE
SET DEFINE OFF;
REM INSERTING into ADMIN.EVENTO_SPORTIVO
SET DEFINE OFF;
REM INSERTING into ADMIN.IMPIEGATO
SET DEFINE OFF;
Insert into ADMIN.IMPIEGATO (ID,CODICE_FISCALE,USERNAME,PASSWORD,DATA_ASSUNZIONE,STIPENDIO,EMAIL,TELEFONO) values ('1','DMRSRG70L06F839N','sdimartino','sergione',to_date('15-JAN-18','DD-MON-RR'),'1800','sergio.dimartino@unina.it',null);
REM INSERTING into ADMIN.LUOGO
SET DEFINE OFF;
Insert into ADMIN.LUOGO (NOME_LUOGO,CITTA,NUM_POSTI) values ('SAN CARLO','NAPOLI','30000');
Insert into ADMIN.LUOGO (NOME_LUOGO,CITTA,NUM_POSTI) values ('PALAPARTENOPE','NAPOLI','3000');
REM INSERTING into ADMIN.PERSONA
SET DEFINE OFF;
Insert into ADMIN.PERSONA (CODICE_FISCALE,NOME,COGNOME,DATA_NASCITA) values ('DMRSRG70L06F839N','Sergio','Di Martino',null);
REM INSERTING into ADMIN.SPORT
SET DEFINE OFF;
Insert into ADMIN.SPORT (NOME_SPORT) values ('CALCIO');
Insert into ADMIN.SPORT (NOME_SPORT) values ('BASKET');
Insert into ADMIN.SPORT (NOME_SPORT) values ('RUGBY');
Insert into ADMIN.SPORT (NOME_SPORT) values ('GOLF');
Insert into ADMIN.SPORT (NOME_SPORT) values ('OLIMPIADI');
Insert into ADMIN.SPORT (NOME_SPORT) values ('NUOTO');
Insert into ADMIN.SPORT (NOME_SPORT) values ('TENNIS');
Insert into ADMIN.SPORT (NOME_SPORT) values ('CRICKET');
Insert into ADMIN.SPORT (NOME_SPORT) values ('BASEBALL');
Insert into ADMIN.SPORT (NOME_SPORT) values ('CICLISMO');
Insert into ADMIN.SPORT (NOME_SPORT) values ('ATLETICA');
REM INSERTING into ADMIN.TIPOLOGIA_EVENTO
SET DEFINE OFF;
Insert into ADMIN.TIPOLOGIA_EVENTO (TIPOLOGIA) values ('MUSICALE');
Insert into ADMIN.TIPOLOGIA_EVENTO (TIPOLOGIA) values ('TEATRO');
Insert into ADMIN.TIPOLOGIA_EVENTO (TIPOLOGIA) values ('SPORTIVO');
Insert into ADMIN.TIPOLOGIA_EVENTO (TIPOLOGIA) values ('ALTRO');
--------------------------------------------------------
--  DDL for Index CITTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."CITTA_PK" ON "ADMIN"."CITTA" ("NOME_CITTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTO_MUSICALE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."EVENTO_MUSICALE_PK" ON "ADMIN"."EVENTO_MUSICALE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."EVENTO_PK" ON "ADMIN"."EVENTO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EVENTO_SPORTIVO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."EVENTO_SPORTIVO_PK" ON "ADMIN"."EVENTO_SPORTIVO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPIEGATO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."IMPIEGATO_PK" ON "ADMIN"."PERSONA" ("CODICE_FISCALE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPIEGATO_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."IMPIEGATO_PK1" ON "ADMIN"."IMPIEGATO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IMPIEGATO_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."IMPIEGATO_UK1" ON "ADMIN"."IMPIEGATO" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LUOGO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."LUOGO_PK" ON "ADMIN"."LUOGO" ("NOME_LUOGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPORT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."SPORT_PK" ON "ADMIN"."SPORT" ("NOME_SPORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPOLOGIA_EVENTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN"."TIPOLOGIA_EVENTO_PK" ON "ADMIN"."TIPOLOGIA_EVENTO" ("TIPOLOGIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EVENTO_SPORTIVO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" MODIFY ("PARTECIPANTE2" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" MODIFY ("PARTECIPANTE1" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" ADD CONSTRAINT "EVENTO_SPORTIVO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" MODIFY ("SPORT" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPORT
--------------------------------------------------------

  ALTER TABLE "ADMIN"."SPORT" ADD CONSTRAINT "SPORT_PK" PRIMARY KEY ("NOME_SPORT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."SPORT" MODIFY ("NOME_SPORT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CITTA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."CITTA" ADD CONSTRAINT "CITTA_PK" PRIMARY KEY ("NOME_CITTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."CITTA" MODIFY ("NOME_CITTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LUOGO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LUOGO" ADD CONSTRAINT "LUOGO_PK" PRIMARY KEY ("NOME_LUOGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."LUOGO" MODIFY ("CITTA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."LUOGO" MODIFY ("NOME_LUOGO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPOLOGIA_EVENTO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."TIPOLOGIA_EVENTO" ADD CONSTRAINT "TIPOLOGIA_EVENTO_PK" PRIMARY KEY ("TIPOLOGIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."TIPOLOGIA_EVENTO" MODIFY ("TIPOLOGIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "ADMIN"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("CODICE_FISCALE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."PERSONA" MODIFY ("COGNOME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PERSONA" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."PERSONA" MODIFY ("CODICE_FISCALE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTO_MUSICALE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO_MUSICALE" ADD CONSTRAINT "EVENTO_MUSICALE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."EVENTO_MUSICALE" MODIFY ("ARTISTA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO_MUSICALE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("TIPOLOGIA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO" ADD CONSTRAINT "EVENTO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("PREZZO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("LUOGO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."EVENTO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table IMPIEGATO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."IMPIEGATO" ADD CONSTRAINT "IMPIEGATO_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("STIPENDIO" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("DATA_ASSUNZIONE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."IMPIEGATO" ADD CONSTRAINT "IMPIEGATO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("CODICE_FISCALE" NOT NULL ENABLE);
  ALTER TABLE "ADMIN"."IMPIEGATO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EVENTO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO" ADD CONSTRAINT "EVENTO_FK1" FOREIGN KEY ("LUOGO")
	  REFERENCES "ADMIN"."LUOGO" ("NOME_LUOGO") ENABLE;
  ALTER TABLE "ADMIN"."EVENTO" ADD CONSTRAINT "EVENTO_FK2" FOREIGN KEY ("TIPOLOGIA")
	  REFERENCES "ADMIN"."TIPOLOGIA_EVENTO" ("TIPOLOGIA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTO_MUSICALE
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO_MUSICALE" ADD CONSTRAINT "EVENTO_MUSICALE_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."EVENTO" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENTO_SPORTIVO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" ADD CONSTRAINT "EVENTO_SPORTIVO_FK1" FOREIGN KEY ("ID")
	  REFERENCES "ADMIN"."EVENTO" ("ID") ENABLE;
  ALTER TABLE "ADMIN"."EVENTO_SPORTIVO" ADD CONSTRAINT "EVENTO_SPORTIVO_FK2" FOREIGN KEY ("SPORT")
	  REFERENCES "ADMIN"."SPORT" ("NOME_SPORT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table IMPIEGATO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."IMPIEGATO" ADD CONSTRAINT "IMPIEGATO_FK1" FOREIGN KEY ("CODICE_FISCALE")
	  REFERENCES "ADMIN"."PERSONA" ("CODICE_FISCALE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LUOGO
--------------------------------------------------------

  ALTER TABLE "ADMIN"."LUOGO" ADD CONSTRAINT "LUOGO_FK1" FOREIGN KEY ("CITTA")
	  REFERENCES "ADMIN"."CITTA" ("NOME_CITTA") ENABLE;
