CREATE SEQUENCE EV_ID_SEQ START WITH 1;

create or replace TRIGGER EV_ID_INCREMENT
BEFORE INSERT ON EVENTO
FOR EACH ROW

BEGIN
  SELECT EV_ID_SEQ.NEXTVAL
  INTO   :new.ID
  FROM  DUAL;
END;


DELETE FROM ARTISTI_EVENTO_MUSICALE WHERE ID=0 AND ARTISTA='LIGABUE';
DELETE FROM EVENTO WHERE ID=0 AND NOME='Concerto Ligabue' AND LUOGO='PALAPARTENOPE' AND DATA=TO_DATE('2018-08-25', 'YYYY-MM-DD') AND PREZZO=40 AND DESCRIZIONE='Concerto di Ligabue al Palapartenope di Napoli il 25/08/18' AND TIPOLOGIA='MUSICALE';


CREATE TABLE ARTISTA 
(
  NOME_ARTISTA VARCHAR2(20) NOT NULL 
, CONSTRAINT ARTISTA_PK PRIMARY KEY 
  (
    NOME_ARTISTA 
  )
  ENABLE 
);


DROP TABLE "ADMIN"."EVENTO_MUSICALE" CASCADE CONSTRAINTS


CREATE TABLE ARTISTI_EVENTO_MUSICALE 
(
  ID NUMBER NOT NULL 
, ARTISTA VARCHAR2(20) NOT NULL 
, CONSTRAINT ARTISTI_EVENTO_MUSICALE_PK PRIMARY KEY 
  (
    ID 
  , ARTISTA 
  )
  ENABLE 
);

ALTER TABLE ARTISTI_EVENTO_MUSICALE
ADD CONSTRAINT ARTISTI_EVENTO_MUSICALE_FK1 FOREIGN KEY
(
  ID 
)
REFERENCES EVENTO
(
  ID 
)
ENABLE;

ALTER TABLE ARTISTI_EVENTO_MUSICALE
ADD CONSTRAINT ARTISTI_EVENTO_MUSICALE_FK2 FOREIGN KEY
(
  ARTISTA 
)
REFERENCES ARTISTA
(
  NOME_ARTISTA 
)
ENABLE;


drop table "ADMIN"."EVENTO_SPORTIVO" cascade constraints 

CREATE TABLE EVENTO_SPORTIVO 
(
  ID NUMBER NOT NULL 
, SPORT VARCHAR2(20) NOT NULL 
, CONSTRAINT EVENTO_SPORTIVO_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE EVENTO_SPORTIVO
ADD CONSTRAINT EVENTO_SPORTIVO_FK1 FOREIGN KEY
(
  ID 
)
REFERENCES EVENTO
(
  ID 
)
ENABLE;

ALTER TABLE EVENTO_SPORTIVO
ADD CONSTRAINT EVENTO_SPORTIVO_FK2 FOREIGN KEY
(
  SPORT 
)
REFERENCES SPORT
(
  NOME_SPORT 
)
ENABLE;


CREATE TABLE ATLETA 
(
  NOME_ATLETA VARCHAR2(20) NOT NULL 
, CONSTRAINT ATLETA_PK PRIMARY KEY 
  (
    NOME_ATLETA 
  )
  ENABLE 
);



CREATE TABLE PARTECIPANTI_EVENTO_SPORTIVO 
(
  ID NUMBER NOT NULL 
, PARTECIPANTE VARCHAR2(20) NOT NULL 
, CONSTRAINT PARTECIPANTI_EVENTO_SPORTI_PK PRIMARY KEY 
  (
    ID 
  , PARTECIPANTE 
  )
  ENABLE 
);

ALTER TABLE PARTECIPANTI_EVENTO_SPORTIVO
ADD CONSTRAINT PARTECIPANTI_EVENTO_SPORT_FK1 FOREIGN KEY
(
  ID 
)
REFERENCES EVENTO
(
  ID 
)
ENABLE;

ALTER TABLE PARTECIPANTI_EVENTO_SPORTIVO
ADD CONSTRAINT PARTECIPANTI_EVENTO_SPORT_FK2 FOREIGN KEY
(
  PARTECIPANTE 
)
REFERENCES ATLETA
(
  NOME_ATLETA 
)
ENABLE;




DROP PROCEDURE "ADMIN"."INS_EVENTO_MUSICALE"

create or replace FUNCTION ins_evento (new_nome varchar2, new_luogo varchar2, new_data date, new_prezzo float, new_descrizione varchar2, new_tipologia varchar2)
return NUMBER
IS
new_id number;

BEGIN

    INSERT INTO Evento(ID, nome, luogo, data, prezzo, descrizione, tipologia)
        VALUES('0', new_nome, new_luogo, new_data, new_prezzo, new_descrizione, new_tipologia);

    SELECT id
        INTO new_id
        FROM Evento
        WHERE nome = new_nome AND luogo = new_luogo AND data = new_data AND prezzo = new_prezzo AND descrizione = new_descrizione AND tipologia=new_tipologia;

RETURN new_id;

END ins_evento;


